# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Mand Kittani
title: System Engineer
email: mandkittani@outlook.com
website: https://mandzukic89.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  mandzukic89
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: mandkittani
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: Summary
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Skilled system engineer with strong background in Linux/Unix and Windows administration. Experince in desiging implmenting and manging cutting-edge deployment automation of cloud resources.
  Dedicated professional with strong track of accurately conducting system repairs, stress-testing the enviornment for any bottleneck issues and troubleshooting.
  Offering exemplary planning, project management and communication talents.

#  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Real time ATS
        #link: github.com/sproogen
        # link_text: Project Website
        #additional_links:
          #- title:  sproogen/modern-resume-theme
            #icon: fab fa-github
            #url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          I started this project as a way of learning <mark>Kotlin</mark> and it became a core component of the application. I have learned many skills through this and been I'm very proud of having this as my senior project.
        description: | # this will include new lines to allow paragraphs
          Developed a real time attendance tracking system using android/java that replaces old traditonal/manual attendance tracking. This application provides adminstrator (Faculty/Professors) and users (Students) their attendace data information, such as class subject/number, track attaendance time and date, track missed date,  notification history, special features for adminstrator allowing them to orgnize, add, remove and edit data.
          Used Kotlin/Java API features, Parse Server to store/attain data.
          Developed an IoT tracking device by using RaspberryPi, I2C LCD, numpad and RFID chip. Some of RESTful API features where implmented to enable communication between the mobile application and the IoT device. As well, Firebase API features were implmented to allow integration to send push notification through the mobile application.


          
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Cloud Evolutions
        link: cloud-evolutions.com
        # link_text: boringcompany.com
        sub_title: Cloud System Engineer
        caption: November 2017 - Present
        quote: >
          Cloud Evolutions provides the platform flexibility your business requires with the security, experience and operational discipline that give you peace of mind.
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: California State University Dominguez Hills
        caption: 2017 - 2019
        sub_title: BS Computer Science
        quote: >
          Established in 1960, CSU Dominguez Hills is a divrse, welcoming community of learners and educators collaborating to change lives and communities for the better.
        description: | # this will include new lines to allow paragraphs
          During my time at CSUDH I learnt most of my key skills that I have taken through my career such as collaberation with classmates and orgnization skill to meet deadlines. I thouroughly enjoyed my time at the university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Cyber Security club and Mozilla Open Student Network club* taking on roles such as *Vice-president* and *Club Treasurer*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in cloud technology and software engineering some of my other interests and hobbies are:
      - Cycling
      - Gaming
      - Custom Keyboards
      - IoT, RPi
#      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

#      Look at this cool image
#      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
